# Generated by Django 4.0.4 on 2022-04-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('segmento', models.CharField(choices=[('F', 'Ensino Fundamental'), ('M', 'Ensino Médio')], default='F', max_length=2)),
                ('ano', models.CharField(choices=[('6', '6º Ano'), ('7', '7º Ano'), ('8', '8º Ano'), ('9', '9º Ano'), ('1', '1º Ano E.M.'), ('2', '2º Ano E.M.'), ('3', '3º Ano E.M.')], default='6', max_length=2)),
                ('nivel', models.CharField(choices=[('Fa', 'Fácil'), ('Me', 'Médio'), ('De', 'Difícil')], default='Fa', max_length=2)),
                ('assunto', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('texto', models.TextField(max_length=1000)),
            ],
        ),
    ]
