# Generated by Django 4.0.4 on 2022-04-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questoes',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='nivel',
            field=models.CharField(choices=[('Fa', 'Fácil'), ('Me', 'Médio'), ('De', 'Difícil')], default='Fa', max_length=3),
        ),
    ]
